name: Build e Test con Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codice sorgente
      uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'

    - name: Esegui build con Maven
      run: mvn -f ${{ github.workspace }}/codice/pmcsn/pom.xml clean install exec:java
