name: Build e Test con Maven

on:
  push:
    branches:
      - main
      - avoid-loop
      - controllerScarico

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codice sorgente
      uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'

    - name: Esegui build con Maven
      run: mvn -f ${{ github.workspace }}/codice/pmcsn/pom.xml clean install exec:java

    - name: Upload csv files
      uses: actions/upload-artifact@v3
      with:
	name: graphs (dati e immagini)
        path: target/graphs

    - name: Configura Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'
        
    - name: Installa dipendenze
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib  # Installa la libreria matplotlib

    - name: Disegna grafici
      run: python codice/pmcsn/graph_drawer.py
